### ISSUE TITLE
Support for providing an alternate credential profile/iam role for a client

### ISSUE THREAD

**Issue by vikshab** [jmaver-plume/kafkajs-msk-iam-authentication-mechanism#27]
It would be great if we were able to provide an alternate IAM role or creds profile for a KafkaJS as it supported currently in Java version https://github.com/aws/aws-msk-iam-auth#specifying-an-alternate-credential-profile-for-a-client

**Comment by jmaver-plume** [comment]
Will check this weekend.

**Comment by awhittier-cribl** [comment]
I would also be interested in seeing an example of how to configure/use the library to assume a role and use the assumed role's credentials for authorization. Thanks!

**Comment by jmaver-plume** [comment]
You can 
- Pass your own credentials provider.
- Set $AWS_PROFILE environment variable.

For more information https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_credential_providers.html#fromnodeproviderchain

**Comment by vikshab** [comment]
@jmaver-plume Thank you for a quick response and adding this feature!
