### ISSUE TITLE
KafkaJSNonRetriableError: Cannot change principals during re-authentication

### ISSUE THREAD

**Issue by jfr992** [jmaver-plume/kafkajs-msk-iam-authentication-mechanism#35]
Hello!

We are getting disconected due to :

KafkaJSNonRetriableError: Cannot change principals during re-authentication from IAM.arn:aws:sts::XXXX:assumed-role/test-role/aws-sdk-js-session-XXXXXX: IAM.arn:aws:sts::XXXXX:assumed-role/test-role/aws-sdk-js-session-1682635894325
    at /usr/src/app/node_modules/kafkajs/src/retry/index.js:55:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    
   is there a way to workaround this?

**Comment by mawaldne** [comment]
Hey @jfr992 , check out: https://github.com/jmaver-plume/kafkajs-msk-iam-authentication-mechanism/issues/20

They have the same error, and setting AWS_ROLE_SESSION_NAME worked for them. Im going to also try the same thing on my side and see if it helps.

**Comment by anilspydra** [comment]
@jmaver-plume 
@mawaldne 

after adding the AWS_ROLE_SESSION_NAME , the authentication is succesful but facing issue with broker pool and getting timeed out

```
{"level":"ERROR","timestamp":"2023-05-04T14:25:02.229Z","logger":"kafkajs","message":"[SaslAuthenticator-AWS_MSK_IAM] Request SaslAuthenticate(key: 36, version: 1) timed out","broker":"b-1.ap-south-1.amazonaws.com"}
{"level":"ERROR","timestamp":"2023-05-04T14:25:02.230Z","logger":"kafkajs","message":"[BrokerPool] Request SaslAuthenticate(key: 36, version: 1) timed out","retryCount":0,"retryTime":535}
{"level":"WARN","timestamp":"2023-05-04T14:25:03.019Z","logger":"kafkajs","message":"[RequestQueue] Response without match","clientId":"blockchain-microservice","broker":"b-1.ap-south-1.amazonaws.com","correlationId":2}
{"level":"ERROR","timestamp":"2023-05-04T14:25:08.052Z","logger":"kafkajs","message":"[SaslAuthenticator-AWS_MSK_IAM] Request SaslAuthenticate(key: 36, version: 1) timed out","broker":"b-1.ap-south-1.amazonaws.com"}
{"level":"ERROR","timestamp":"2023-05-04T14:25:08.053Z","logger":"kafkajs","message":"[BrokerPool] Request SaslAuthenticate(key: 36, version: 1) timed out","retryCount":1,"retryTime":1214}
{"level":"WARN","timestamp":"2023-05-04T14:25:09.896Z","logger":"kafkajs","message":"[RequestQueue] Response without match","clientId":"blockchain-microservice","broker":"b-1.ap-south-1.amazonaws.com","correlationId":4}
{"level":"INFO","timestamp":"2023-05-04T14:25:14.134Z","logger":"kafkajs","message":"[SaslAuthenticator-AWS_MSK_IAM] Authentication response","authenticateResponse":{"version":"2020_10_22","request-id":"4a26ca26-38fa-483a-bf2f-bd9e07f5a3b2"}}
{"level":"INFO","timestamp":"2023-05-04T14:25:14.134Z","logger":"kafkajs","message":"[SaslAuthenticator-AWS_MSK_IAM] SASL AWS_MSK_IAM authentication successful","broker":"b-1.ap-south-1.amazonaws.com"}
2023-05-04 19:55:19:5519 - [debug] - : error-in-consumer: Request Metadata(key: 3, version: 6) timed out
```

**Comment by adarshbalu** [comment]
{"level":"ERROR","timestamp":"2023-08-11T13:24:37.575Z","logger":"kafkajs","message":"[Consumer] Crash: KafkaJSNonRetriableError: Cannot change principals during re-authentication from IAM.arn:aws:sts::020260453790:assumed-role/msk-full-iam/aws-sdk-js-session-1691756680572: IAM.arn:aws:sts::020260453790:assumed-role/msk-full-iam/aws-sdk-js-session-1691760272714","groupId":"group","stack":"KafkaJSNonRetriableError: Cannot change principals during re-authentication from IAM.arn:aws:sts::020260453790:assumed-role/msk-full-iam/aws-sdk-js-session-1691756680572: IAM.arn:aws:sts::020260453790:assumed-role/msk-full-iam/aws-sdk-js-session-1691760272714\n    at /home/node/app/node_modules/kafkajs/src/retry/index.js:55:18\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
