### ISSUE TITLE
KafkaJSNonRetriableError: Cannot change principals during re-authentication

### ISSUE THREAD

**Issue by BDeus** [jmaver-plume/kafkajs-msk-iam-authentication-mechanism#42]
Hi,
i have the same issue than https://github.com/tulios/kafkajs/issues/1582
Does anyone run KafkaConsumer with IAM auth on a K8s pod and have this kind of issue on re-authentification ?

**Comment by BDeus** [comment]
it seems than same issue as been automatically close 
https://github.com/jmaver-plume/kafkajs-msk-iam-authentication-mechanism/issues/35 and https://github.com/jmaver-plume/kafkajs-msk-iam-authentication-mechanism/issues/20  

Is it possible to add documentation around AWS_ROLE_SESSION_NAME ?

**Comment by cakesoft-yatindra** [comment]
Closing this issue as setting `AWS_ROLE_SESSION_NAME` in environment variable to any static value resolves the error.
