### ISSUE TITLE
Comparison to aws-msk-iam-sasl-signer-js

### ISSUE THREAD

**Issue by gabegorelick** [jmaver-plume/kafkajs-msk-iam-authentication-mechanism#45]
AWS recently released https://github.com/aws/aws-msk-iam-sasl-signer-js as their official solution for MSK IAM with kafkajs. I haven't seen an official announcement, but they are rolling out support to existing and new MSK clusters (https://github.com/aws/aws-msk-iam-sasl-signer-js/issues/17). The docs also reference it now: https://docs.aws.amazon.com/msk/latest/developerguide/iam-access-control.html.

It would be nice to document how kafkajs-msk-iam-authentication-mechanism compares to AWS's solution.

**Comment by BDeus** [comment]
I think it's a simple official replacement by AWS
Annoucement is here: https://aws.amazon.com/blogs/big-data/amazon-msk-iam-authentication-now-supports-all-programming-languages/
