### ISSUE TITLE
What is the hashed payload for ?

### ISSUE THREAD

**Issue by TabraizChel** [jmaver-plume/kafkajs-msk-iam-authentication-mechanism#9]
In AuthenticationPayloadCreator there's a constant called HASHED_PAYLOAD. What is this used for ?

**Comment by jmaver-plume** [comment]
It's the value of hex encoded, SHA256 hashed empty string.
For more information you can look at https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html.
